### PR TITLE
Feat cart view

### PR DESCRIPTION
**Pull request by mxng**
## Why

This pull request is needed because:

We need a cart

## What

This pull request introduces the following:

Cart can work on LOCAL STORAGE

## How to Test

Go to the restaurants show page and click on the 'add to cart' and play with it

### CODE REVIEW

**Review by TeeWhyKay — APPROVED** [review]
looks great! nice local storage feature

**Comment by mxng** [comment]
image


@tjw0612 what it looks like now

**Review by tjw0612 — APPROVED** [review]
thanks, will make changes to price position

**Review by TeeWhyKay — APPROVED** [review]
looks great

**Review by amelialimyh — APPROVED** [review]
Looks good

**Pull request merged**
